version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install nginx -y
  build:
    commands:
      - cp index.html /var/www/html
  post_build:
    commands:
      - echo "Configuring NGINX"  # Add actual NGINX configuration here
artifacts:
  files:
    - "**/*"
